### PR TITLE
Downgrade elasticsearch-rest-high-level-client to 6.8.3

### PR DESCRIPTION
**Pull request by alxsap**
fixes https://github.com/SAP/elasticsearch-logs-plugin/issues/11

Needs to be tested, with Elasticsearch 6.x and higher versions.

### CODE REVIEW

**Comment by alxsap** [comment]
Tested with Elasticsearch 7.3. - no issues with basic write and read logs.

**Comment by alxsap** [comment]
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-compatibility.html

> It is recommended to **upgrade the High Level Client when upgrading the Elasticsearch cluster to a new major version**, as REST API breaking changes may cause unexpected results depending on the node that is hit by the request, and newly added APIs will only be supported by the newer version of the client. The client should always be updated last, once all of the nodes in the cluster have been upgraded to the new major version.

This means the change in this PR is not recommended, although tests with 7.x did not show any issues.

**Comment by mawinter69** [comment]
Probably we use only a very small part of the offered API. If it works we might consider staying on the older version. In any case it must be clearly documented that a version mismatch is a potential problem.
As long as the java api is identical for the things we use we could extract the ES rest client into a separate jenkins plugin and then have versions for ES 6 and ES 7. 
This would allow to run the plugin without changes with a fitting version. This of course raises the question who would maintain this additional plugin.

**Comment by alxsap** [comment]
I moved the conversation to a separate issue: https://github.com/SAP/elasticsearch-logs-plugin/issues/13

**Comment by alxsap** [comment]
I introduces a release branch `rel-ES6.x` for now and I changed the base of this pull request to this branch. I think this is how we should handle it as long as there is no better solution for https://github.com/SAP/elasticsearch-logs-plugin/issues/13.

**Comment by mawinter69** [comment]
Whatever we do there is no optimal solution. I'm in favor of staying on 6 if our tests show no issues when running against a 7 instance. This offers the lowest efforts for us. Of course it must be clearly documented that a newer version might cause troubles in the future.

**Pull request merged**
